services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - "8000:8000"
    entrypoint:
      - /surreal
      - start
      - -u root
      - -p root
      - --allow-all
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.config/nginx/conf.d:/etc/nginx/conf.d
      - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/frontend/dist:/usr/share/nginx/html