services:
  
  surrealdb:
    image: surrealdb/surrealdb:latest
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - "8000:8000"
    volumes:
      - .docker/db:/var/lib/surrealdb
    entrypoint:
      - /surreal 
      - start 
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD