services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - "8000:8000"
    entrypoint:
      - /surreal
      - start
      - -u $DB_USER
      - -p $DB_PASS
      - --allow-all
      - --no-identification-headers
      - --no-banner
  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.config/nginx/conf.d:/etc/nginx/conf.d
      - ./.config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"